USE sakila;
#Write SQL queries to perform the following tasks using the Sakila database:
#List the number of films per category.

SELECT category_id, COUNT(*) AS number_of_films
FROM film_category
GROUP BY category_id
ORDER BY number_of_films DESC;

#Retrieve the store ID, city, and country for each store.
SELECT store_id, city, country
FROM  store AS s
INNER JOIN city AS c 
ON s.address_id = c.city_id
INNER JOIN country co 
ON c.country_id = co.country_id;

#Calculate the total revenue generated by each store in dollars.
SELECT store_id, SUM(p.amount) AS total_revenue
FROM store AS s
INNER JOIN payment AS p 
ON s.store_id = p.payment_id 
GROUP BY s.store_id;

#Determine the average running time of films for each category.
SELECT c.category_id, AVG(f.length) AS average_running_time
FROM category AS c
LEFT JOIN film_category AS fc 
ON c.category_id = fc.category_id
LEFT JOIN film AS f 
ON f.film_id = fc.film_id
GROUP BY c.category_id;